name: Run All Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
      - name: Run Backend Tests (Pytest)
        run: pytest

      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      
      - name: Install Node dependencies
        run: npm install

      
      - name: Install Playwright Browsers
        run: npx @playwright/test install --with-deps

      
      - name: Start Flask Server in background
        run: |
          python app.py &
          sleep 5

      - name: Serve frontend files
        run: |
          npx serve frontend -l 5500 &
          sleep 3          

          
      - name: Run Frontend Tests (Playwright)
        run: npx playwright test


      - name: Run API Tests (Newman)
        run: npx newman run "Taskmaster API.postman_collection.json"